# Generated by Django 4.1.6 on 2023-03-02 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_imagem_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
